package com.davina.core.dao;

import com.davina.core.pojo.log.PayLog;
import java.util.List;

public interface PayLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String outTradeNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbggenerated
     */
    int insert(PayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbggenerated
     */
    PayLog selectByPrimaryKey(String outTradeNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbggenerated
     */
    List<PayLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PayLog record);
}