package com.davina.core.dao;

import com.davina.core.pojo.PayLog;
import com.davina.core.pojo.PayLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PayLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbggenerated
     */
    int countByExample(PayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbggenerated
     */
    int deleteByExample(PayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String outTradeNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbggenerated
     */
    int insert(PayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbggenerated
     */
    int insertSelective(PayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbggenerated
     */
    List<PayLog> selectByExample(PayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbggenerated
     */
    PayLog selectByPrimaryKey(String outTradeNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PayLog record, @Param("example") PayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PayLog record, @Param("example") PayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PayLog record);
}