package com.davina.core.dao;

import com.davina.core.pojo.seckill.SeckillGoods;
import java.util.List;

public interface SeckillGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated
     */
    int insert(SeckillGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated
     */
    SeckillGoods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated
     */
    List<SeckillGoods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SeckillGoods record);
}